spring:
  application:
    name: product-service
  datasource:
    #driverClassName: com.hsqldb.jdbcDriver
    url: jdbc:hsqldb:hsql://localhost/storenear
    username:
    password:
  jpa:
   databasePlatform: org.hibernate.dialect.HSQLDialect
   hibernate.ddl-auto: update
   show-sql: true
  
     
server:
  port: 8082
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry : true
  serviceUrl:
    defaultZone: http://localhost:8888/eureka
    instance:
     preferredIpAddress: true